[package]
name = "helix-component"
version = "0.1.0"
edition = "2021"


[dependencies]
# wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.3.0" }
wasmtime = {version ="17.0.0", features = ["component-model"] }
