package helix:plugin;

interface editor {
  record document {
    line-number: u64,
    filename: option<string>,
  }

  get-git-remote: func() -> result<string, string>;
  clipboard-copy: func(content: string) -> result<string, string>;
  current-document: func() -> option<document>;
}

world plugin {
  import editor;

  export handle-command: func(command: string) -> result<string, string>;
  export commands: func(command: string) -> list<string>;
}

world host {
  export editor;
}
